config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  resources :tags

  resources :tasks, only: [:edit, :update, :destroy]

  resources :tasks
  resources :projects
  devise_for :users
  resources :users, only: :index
  get 'users/profile'
  get 'tasks/:id/toggle_done', to: "tasks#toggle_done", as: 'toggle_done'
  get "pages/index"
  root "pages#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project

  has_one_attached :file

  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags

  validates :title, presence: true
  validates :solver_id, presence: true
  scope :for_user, ->(user) { where(user_id: user.id) }

  def self.ransackable_attributes(auth_object = nil)
    [ "title"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["project", "tags", "task_tags", "user"]
  end
  accepts_nested_attributes_for :tags

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.includes([:file_attachment, :tags, :project]).for_user(current_user)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new

    @task = Task.new

  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create

    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def toggle_done
    @task = Task.find(params[:id])
    @task.is_done = !@task.is_done
    @task.save
    redirect_back(fallback_location: root_path)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title,:solver_id,:state_advanced, :file,:description, :is_done, :user_id, :project_id, :own_id,tag_ids: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def render_filtered_tasks(tasks, tasks_to_show)
    return tasks if tasks_to_show == 'all'

    if tasks_to_show == 'done'
      tasks.select { |task| task.is_done }
    elsif tasks_to_show == 'not_done'
      tasks.reject { |task| task.is_done }
    else
      tasks
    end
  end
  def has_file(task)
    i = task.file.blank? ? t(:no_file) : link_to(t(:view_file), task.file)
  end
  def has_description(task)
    i=task.description.blank? ? t(:no_description) : task.description
  end
  def tags(task)
    if !task.tags.blank?
      task.tags.map(&:title).join(', ')
    else
      t(:no_tags)
      end
  end

end

app/views/tasks/_form.html.haml
.container.m-0
  = simple_form_for @task, html: { multipart: true } do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      = f.input :title, label: t(:title)
      = f.input :description, label: t(:description)
      = f.input :is_done, label: t(:is_done)
      = f.input :user_id,
              :input_html => { value:current_user.id},
              as: :hidden
      -if params[:project_id] != nil
        = f.input :project_id,
                  :input_html => { value:params[:project_id]},
                as: :hidden
      -if !Tag.for_user(current_user).blank?
        =f.association :tags,collection:Tag.for_user(current_user), as: :check_boxes,item_wrapper_class: 'checkbox_container',label: t(:tags)
      -else
        %b
          =t(:no_tags)
        %br
        = link_to t(:user_ads_new_tag), new_tag_path, class: "btn btn-outline-dark"

      =f.input :file, as: :file, label: t(:file)
      =f.input :solver_id ,
              :input_html => { value:current_user.id},
              as: :hidden
      =f.input :state_advanced, label: t(:state), collection:["novy", "ceka na klienta", "v reseni", "hotovo"],selected: "novy"
      = f.input :solver_id, collection: User.all, label_method: :name, value_method: :id, include_blank: true,required: true,selected: current_user.id

    .form-actions
      = f.button :submit, class: "btn btn-success"

app/views/tasks/_form.html.slim
= simple_form_for @task ,html: { multipart: true } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  div style="margin-left: 20px"
    .form-inputs
      = f.input :title, label: t(:title)
      = f.input :description, label: t(:description)
      = f.input :is_done, label: t(:is_done)
      = f.input :user_id,
              :input_html => { value:current_user.id},
              as: :hidden
      -if params[:project_id] != nil
        = f.input :project_id,
                  :input_html => { value:params[:project_id]},
                as: :hidden
      -if !Tag.for_user(current_user).blank?
        =f.association :tags,collection:Tag.for_user(current_user), as: :check_boxes,item_wrapper_class: 'checkbox_container',label: t(:tags)
      -else
        b
          =t(:no_tags)
        br
        = link_to t(:user_ads_new_tag), new_tag_path, class: "btn btn-outline-dark"

      =f.input :file, as: :file, label: t(:file)
      =f.input :solver_id ,
              :input_html => { value:current_user.id},
              as: :hidden
      =f.input :state_advanced, label: t(:state), collection:["novy", "ceka na klienta", "v reseni", "hotovo"],selected: "novy"
      = f.input :solver_id, collection: User.all, label_method: :name, value_method: :id, include_blank: true,required: true,selected: current_user.id

  div style="margin-left: 20px"
    .form-actions
      = f.button :submit, class:"btn btn-success"

app/views/tasks/_task.html.haml
- if task.user == current_user
  .task#{dom_id task}
    %p
      %strong Title:
        = task.title
    %p
      %strong Description:
        = task.description
    %p
      %strong Is done:
        = task.is_done
    %p
      %strong User:
        = task.user_id
    %p
      %strong Project:
        = task.project_id

app/views/tasks/_task.html.slim
-if task.user==current_user
  div id="#{dom_id task}"
    p
      strong Title:
      =< task.title
    p
      strong Description:
      =< task.description
    p
      strong Is done:
      =< task.is_done
    p
      strong User:
      =< task.user_id
    p
      strong Project:
      =< task.project_id

app/views/tasks/edit.html.haml
%h1= t(:edit_task)

= render "form", task: @task

%br

.container
  = link_to t(:back_to_tasks), tasks_path, class: "btn btn-outline-dark"
  |
  = link_to t(:show_projects), projects_path, class: "btn btn-outline-primary"

app/views/tasks/edit.html.slim
h1 =t(:edit_task)

== render "form", task: @task

br

div

  =< link_to t(:back_to_tasks), tasks_path,class:"btn btn-outline-dark"
  '|
  =link_to t(:show_projects),projects_path, class:"btn btn-outline-primary"

app/views/tasks/index.html.haml
.container.m-0
  %p(style="color: green")= notice

  - if !@tasks.blank?
    %h2= t(:tasks)
    %table.table.thead-dark
      %thead
        %tr
          %th= t(:title)
          %th= t(:description)
          %th= t(:tags)
          %th= t(:project)
          %th= t(:state)
          %th= t(:delete)
          %th= t(:edit_task)
          %th=t(:file)
          %th=t(:solver)

      %tbody
        - @tasks.each do |task|
          %tr
            %th= task.title
            %th= has_description(task)
            %th= tags(task)
            %th= task.project.title
            %th= task.state_advanced
            %th= button_to t(:delete_task), task_path(task), method: :delete, class: "btn btn-outline-danger"


            %th= link_to t(:edit_task), edit_task_path(task), class: "btn btn-dark"
            %th= has_file(task)
            %th= (User.find(task.solver_id)).name
  - else
    %b= t(:no_tasks)

app/views/tasks/index.html.slim
p style="color: green" = notice


-if !@tasks.blank?



  h2 = t(:tasks)
  table class='table'
    thead class="thead-dark"
      tr
        th = t(:title)
        th = t(:description)
        th = t(:tags)
        th = t(:project)
        //th = t(:done)
        //th = t(:state)
        th= t(:state)
        th = t(:delete)
        th = t(:edit_task)
        th =t(:file)
        th =t(:solver)

    -@tasks.each do |task|



      tbody
        tr
          th = task.title
          th=has_description(task)
          th=tags(task)
          th = task.project.title
          //th = done(task.is_done)
          //th = link_to(t(!task.is_done ? :done : :todo), toggle_done_path(id: task.id), class: "btn btn-outline-success")
          th=task.state_advanced
          th = button_to t(:delete_task), task_path(task), method: :delete, :alert => "You haz errors!", class: "btn btn-outline-danger"
          th = link_to t(:edit_task),edit_task_path(task), class:"btn btn-dark"
          th =has_file(task)
          th =(User.find(task.solver_id)).name
-else
  b=t(:no_tasks)

app/views/tasks/new.html.haml
%h1= t(:new_task)

= render "form", task: @task

%br

.container.m-0
  = link_to t(:back_to_tasks), tasks_path, class: "btn btn-outline-dark"
  |
  = link_to t(:show_projects), projects_path, class: "btn btn-outline-primary"

app/views/tasks/new.html.slim
h1 =t(:new_task)

== render "form", task: @task
=
br

div
  = link_to t(:back_to_tasks), tasks_path, class:"btn btn-outline-dark"
  '|
  = link_to t(:show_projects), projects_path, class: "btn btn-outline-primary"

app/views/tasks/show.html.haml
.container
  %p(style="color: green")= notice

  = render @task

  .actions
    = link_to t(:edit_task), edit_task_path(@task), class: "btn btn-outline-success"
    |
    = link_to t(:back_to_tasks), tasks_path, class: "btn btn-outline-dark"

    = button_to t(:destroy_task), @task, method: :delete, class: "btn btn-danger"

app/views/tasks/show.html.slim
p style="color: green" = notice

== render @task

div
  => link_to t(:edit_task), edit_task_path(@task),class:"btn btn-outline-success"
  '|
  =< link_to t(:back_to_tasks), tasks_path,class:"btn btn-outline-dark"

  = button_to t(:destroy_task), @task, method: :delete,class:"btn btn-danger"