config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  resources :tags

  resources :tasks, only: [:edit, :update, :destroy]

  resources :tasks
  resources :projects
  devise_for :users
  resources :users, only: :index
  get 'users/profile'
  get 'tasks/:id/toggle_done', to: "tasks#toggle_done", as: 'toggle_done'
  get "pages/index"
  root "pages#index"
end

app/views/pages/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"}= t(:app_name)
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "#"}
          = link_to t(:home), root_path, class: "navbar-brand"
          %span.sr-only
      - if user_signed_in?

        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:new_project),new_project_path, class: "btn btn-outline-light"
            %span.sr-only
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:show_projects),projects_path, class: "btn btn-outline-light"
            %span.sr-only
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:tags),tags_path, class: "btn btn-outline-light"
            %span.sr-only
        %li.nav-item
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:show_tasks),tasks_path, class: "btn btn-outline-light"
            %span.sr-only
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:all_users),users_path, class: "btn btn-outline-light"
            %span.sr-only
        %li.nav-item
          %a.nav-link{:href => "#", :style => "color:white"}
            %b= t(:nav_message, user:current_user.name, project:current_user.projects.size)
        %li
          = render 'search/form'

        %li
          .dropdown
            %button.btn.btn-secondary.p-0{type: "button", id: "dropdownMenuButton", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false", class: "rounded-circle"}

              = image_tag(current_user.avatar_thumbnail(75,current_user),class: "rounded-circle border border-primary ")

            .dropdown-menu.dropdown-menu-right
              %a.dropdown-item{href: "#"}
                = link_to t(:signout), destroy_user_session_path,:method => :get, class: "btn btn-outline-dark"
              %a.dropdown-item{href: "#"}
                = link_to t(:edit), edit_user_registration_path, class: "btn btn-outline-dark"
              %a.dropdown-item{href: "#"}
                = link_to t(:profile), users_profile_path, class: "btn btn-outline-dark"



      - else
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:signup), new_user_registration_path, class: "btn btn-outline-success"
            %span.sr-only
        %li.nav-item
          %a.nav-link{:href => "#"}
            = link_to t(:signin), new_user_session_path, class: "btn btn-outline-success"
            %span.sr-only

app/views/pages/index.html.haml
=I18n.t :welcome

app/views/pages/index.html.slim
=I18n.t :welcome