config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  resources :tags

  resources :tasks, only: [:edit, :update, :destroy]

  resources :tasks
  resources :projects
  devise_for :users
  resources :users, only: :index
  get 'users/profile'
  get 'tasks/:id/toggle_done', to: "tasks#toggle_done", as: 'toggle_done'
  get "pages/index"
  root "pages#index"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :position, presence: true
  scope :for_user, ->(user) { where(user_id: user.id) }

  belongs_to :user
  has_many :tasks, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    [ "title"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["project", "tags", "task_tags", "user"]
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only:[:edit,:update,:destroy]
  # GET /projects or /projects.json
  def index

    @pagy, @projects = pagy_countless(Project.for_user(current_user).includes(:tasks => [:file_attachment]).order(position: :asc), items: 1)
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    respond_to do |format|

    if current_user.tasks.blank?
      @project.destroy

        format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
    else

        format.html { redirect_to projects_url, notice: "Project can not be destroyed." }

      end
    end
    end
  def correct_user
    @project=current_user.projects.find_by(id: params[:id])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      redirect_to projects_path, notice: "Not authorized" if @project.nil?
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title,:user_id, :position, :creation_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def done(is_done)
    if is_done
      t(:done_task)
    else
      t(:not_done_task)
    end

  end
  def has_file(task)
    i = task.file.blank? ? t(:no_file) : link_to(t(:view_file), task.file)
  end
  def has_description(task)
    i=task.description.blank? ? t(:no_description) : task.description
  end
  def has_tags(task)
    i=!task.tags.blank? ? t(:no_tags) : task.tags.map(&:title).join(', ')
  end
end

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  = f.error_notification
  - if f.object.errors[:base].present?
    = f.error_notification message: f.object.errors[:base].to_sentence
  %div{style: "margin-left: 20px"}
    .form-inputs
      = f.input :title, label: t(:title), required: true
      = f.input :position, label: t(:position), required: true
      = f.input :user_id, required: true, input_html: { value: current_user.id }, id: :project_user_id, as: :hidden
      = f.input :creation_date, required: true, input_html: { value: Date.today }, as: :hidden

  %div{style: "margin-left: 20px"}
    .form-actions
      = f.button :submit, class: 'btn btn-success'

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  div style="margin-left: 20px"
    .form-inputs
      = f.input :title, label: t(:title),
              required: true
      = f.input :position,label: t(:position),
              required: true
      = f.input :user_id,
              required: true,
              :input_html => { value:current_user.id},
              id: :project_user_id,
              as: :hidden
      = f.input :creation_date,
              required: true,
              input_html: { value: Date.today },
              as: :hidden


  div style="margin-left: 20px"
    .form-actions
      = f.button :submit, class:'btn btn-success'

app/views/projects/_project.html.haml
.project.id:project
  %h5
    = "Jmeno:"+project.title.to_s
    %br
    = t(:created_at) + project.creation_date.to_s
    %br
    = t(:position) + " :" + project.position.to_s

  = link_to t(:edit_project), edit_project_path(project), class: "btn btn-outline-dark"
  = link_to t(:new_task), new_task_path(:project_id => project.id), class: "btn btn-outline-success"
  = button_to t(:delete_project), project_path(project), method: :delete, form: { data: { turbo_confirm: 'Are you sure you want to delete this project?' } }, class: "btn btn-outline-danger"

  %br

  - if !project.tasks.blank?
    .tasks
      %p
      %h2= t(:tasks)

      %table.table.thead-dark
        %thead
          %tr
            %th= t(:title)
            %th= t(:description)
            %th= t(:number_of_tags)
            %th= t(:state)
            %th= t(:edit_task)
            %th= t(:delete)
            %th= t(:file)
            %th= t(:solver)

        %tbody
          - project.tasks.each do |task|
            %tr
              %th= task.title
              %th= has_description(task)
              %th= task.tags.size
              %th= task.state_advanced
              %th= link_to t(:edit_task), edit_task_path(task), class: "btn btn-outline-dark"
              %th= button_to t(:delete_task), task_path(task), method: :delete, form: { data: { turbo_confirm: 'Are you sure' } }, class: "btn btn-outline-danger"
              %th= has_file(task)
              %th= (User.find(task.solver_id)).name
  - else
    %b= t(:no_tasks_for_project)

app/views/projects/_project.html.slim
  div id="#{dom_id project}"

    h4
      =< project.title
      br
      = t(:created_at)+project.creation_date.to_s
    p
      h5 =t(:position) +" :"+ project.position.to_s


    = link_to t(:edit_project), edit_project_path(project),class:"btn btn-outline-dark"
    =link_to t(:new_task),new_task_path(:project_id => project.id),class:"btn btn-outline-success"
    br


    -if !project.tasks.blank?
      div
        = button_to t(:delete_project), project_path(project), method: :delete, form: { data: { turbo_confirm: 'Are you sure you want to delete this project?' } }, class: "btn btn-outline-danger"
      p
        h2 = t(:tasks)


      table class='table'
        thead class="thead-dark"
          tr
            th =t(:title)
            th =t(:description)
            th =t(:number_of_tags)
            //th =t(:done)
            //th =t(:state)
            th =t(:state)
            th =t(:edit_task)
            th =t(:delete)
            th =t(:file)
            th =t(:solver)


        - project.tasks.each do |task|

          tbody
            tr
              th =task.title
              th =has_description(task)
              th =task.tags.size
              //th =done(task.is_done)
              //th =link_to(t(!task.is_done ? :done : :todo), toggle_done_path(id: task.id), class: "btn btn-outline-success")
              //advanced_state
              th =task.state_advanced
              th
                = link_to t(:edit_task),edit_task_path(task), class:"btn btn-outline-dark"
              th = button_to t(:delete_task), task_path(task), method: :delete, form: { data: { turbo_confirm: 'Are you sure' } }, class: "btn btn-outline-danger"


              th =has_file(task)
              th =(User.find(task.solver_id)).name
    -else
      b =t(:no_tasks_for_project)

app/views/projects/edit.html.haml
%h1= t(:edit_project)

= render "form", project: @project

%br

%div
  = link_to t(:back_to_projects), projects_path, class: "btn btn-outline-dark"

app/views/projects/edit.html.slim
h1 =t(:edit_project)

== render "form", project: @project

br

div

  =< link_to t(:back_to_projects), projects_path, class:"btn btn-outline-dark"

app/views/projects/index.html.slim
p style="color: green" = notice


-if !@projects.blank?
  h1 =t(:projects)
  == pagy_nav(@pagy)


  #projects
  = turbo_frame_tag :projects do
    ==render @projects



  = turbo_frame_tag :pagination,
          loading: :lazy,
          src: projects_path(format: :turbo_stream)
- else
  p
    b = t(:no_user_projects)
    br
    =link_to t(:new_project),new_project_path, class:"btn btn-outline-dark"

app/views/projects/index.turbo_stream.haml
= turbo_stream.append(:projects) do
  = render @projects


= turbo_stream.replace(:pagination) do
  - if @pagy.next.present?
    = turbo_frame_tag(:pagination,
            loading: :lazy,
            src: projects_path(format: :turbo_stream, page: @pagy.next))

app/views/projects/new.html.haml
%h1= t(:new_project)

= render "form", project: @project

%br

app/views/projects/new.html.slim
h1 =t(:new_project)

== render "form", project: @project

br

app/views/projects/show.html.haml
%p{style: "color: green"}= notice

== render @project

%div
  = link_to t(:new_task), new_task_path(project_id: @project.id), class: "btn btn-outline-success"
  - if !@project.tasks.blank?
    = button_to t(:destroy_this_project), @project, method: :delete, class: "btn btn-danger"

app/views/projects/show.html.slim
p style="color: green" = notice



==render @project
div


  =link_to t(:new_task),new_task_path(:project_id => @project.id),class:"btn btn-outline-success"
  -if !@project.tasks.blank?
    = button_to t(:destroy_this_project), @project, method: :delete,class:"btn btn-danger"