config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  resources :tags

  resources :tasks, only: [:edit, :update, :destroy]

  resources :tasks
  resources :projects
  devise_for :users
  resources :users, only: :index
  get 'users/profile'
  get 'tasks/:id/toggle_done', to: "tasks#toggle_done", as: 'toggle_done'
  get "pages/index"
  root "pages#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags, dependent: :destroy
  has_many :tasks, through: :task_tags

  scope :for_user, ->(user) {where(user_id: user.id)}

  def self.ransackable_attributes(auth_object = nil)
    [ "title"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["project", "tags", "task_tags", "user"]
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.for_user(current_user)
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:title, :user_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= simple_form_for @tag do |f|
  = f.error_notification
  - if f.object.errors[:base].present?
    = f.error_notification message: f.object.errors[:base].to_sentence

  .form-inputs
    = f.input :title, label: t(:title)
    = f.input :user_id, input_html: { value: current_user.id }, as: :hidden

  .form-actions
    = f.button :submit, t(:new_tag)

app/views/tags/_form.html.slim
= simple_form_for(@tag) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, label: t(:title)
    = f.input :user_id,
            :input_html => { value:current_user.id},
            as: :hidden
  .form-actions
    = f.button :submit, t(:new_tag)

app/views/tags/_tag.html.haml
#tag
  %p
    %strong Title:
      = tag.title
  %p
    %strong User:
      = tag.user_id

app/views/tags/_tag.html.slim
div id="#{dom_id tag}"
  p
    strong Title:
    =< tag.title
  p
    strong User:
    =< tag.user_id

app/views/tags/edit.html.haml
%h1 Editing tag

= render "form", tag: @tag

%br

.container
  = link_to "Show this tag", @tag, class: "btn btn-outline-success"
  |
  = link_to "Back to tags", tags_path, class: "btn btn-outline-dark"

app/views/tags/edit.html.slim
h1 Editing tag

== render "form", tag: @tag

br

div
  => link_to "Show this tag", @tag,class:"btn btn-outline-success"
  '|
  =< link_to "Back to tags", tags_path,class:"btn btn-outline-dark"

app/views/tags/index.html.haml
.container.m-0
  %p

  - if !@tags.blank?
    %h2= t(:tags)
    %table.table.thead-dark
      %tr
        %th= t(:title)
        %th= t(:tag_action)

      %tbody
        - @tags.each do |tag|
          %tr
            %th= tag.title
            %th= link_to t(:edit_tag), tag, class: "btn btn-outline-success"

    = link_to t(:new_tag), new_tag_path, class: "btn btn-outline-dark"

  - else
    %b
      = t(:no_tags)
    %br
    = link_to t(:user_ads_new_tag), new_tag_path, class: "btn btn-outline-dark"

app/views/tags/index.html.slim
p style="color: green" = notice




-if !@tags.blank?
  h2 = t(:tags)
  table class='table'
    thead class="thead-dark"
      tr
        th = t(:title)
        th = t(:tag_action)

    tbody
      - @tags.each do |tag|
        tr
          th = tag.title
          th = link_to t(:edit_tag), tag, class:"btn btn-outline-success"

  = link_to t(:new_tag), new_tag_path, class:"btn btn-outline-dark"
-else
  b
    =t(:no_tags)
  br
  =link_to t(:user_ads_new_tag), new_tag_path, class:"btn btn-outline-dark"

app/views/tags/new.html.haml
%h1= t(:new_tag)

= render "form", tag: @tag

%br

.container
  = link_to t(:back_to_tags), tags_path, class: "btn btn-outline-dark"

app/views/tags/new.html.slim
h1 =t(:new_tag)

== render "form", tag: @tag

br

div
  = link_to t(:back_to_tags), tags_path, class:"btn btn-outline-dark"

app/views/tags/show.html.haml
.container
  %p(style="color: green")= notice

  = render @tag

  .btn-toolbar
    = link_to t(:edit_tag), edit_tag_path(@tag), class: "btn btn-outline-success"
    = link_to t(:back_to_tags), tags_path, class: "btn btn-outline-dark"

    = button_to t(:destroy_tag), @tag, method: :delete, class: "btn btn-danger"

app/views/tags/show.html.slim
p style="color: green" = notice

== render @tag

div
  => link_to t(:edit_tag), edit_tag_path(@tag),class:"btn btn-outline-success"
  '|
  =< link_to t(:back_to_tags), tags_path,class:"btn btn-outline-dark"

  = button_to t(:destroy_tag), @tag, method: :delete,class:"btn btn-danger"